name: ubuntu-iso
summary: Download the latest Ubuntu ISOs
description: |
    This is used to download Ubuntu ISOs and verify the download. The
    SHA256 hash of the ISO is downloaded and the signed GPG file used
    to verify that the file is valid. Once downloaded, the hash of the
    ISO is compared to the expected value and either confirmed or the
    file is deleted.

version: git
grade: stable
confinement: strict
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ubuntu-iso:
        command: bin/ubuntu-iso
        plugs:
            - home
            - network

parts:
    ubuntu-iso:
        plugin: python
        source: https://github.com/powersj/ubuntu-iso
        source-type: git
