name: ubuntu-iso-download
summary: Download the latest Ubuntu ISOs
description: |
    This is used to download Ubuntu ISOs and verify hash of the
    download. The following flavors are available

    * Ubuntu Desktop
    * Ubuntu Server
    * Kubuntu
    * Lubuntu
    * Ubuntu Budgie
    * Ubuntu Kylin
    * Ubuntu MATE
    * Ubuntu Studio
    * Xubuntu

    The release is the codename and must be a currently supported
    release and defaults to the latest LTS. Only the amd64
    architecture is supported for download.

    For verification, the SHA-256 hash file and signed GPG has file are
    both downloaded. The signed GPG file is used to verify that the
    hash file is valid and the expected hash saved. Once the ISO is
    downloaded, the SHA-256 hash is calculated and compared to the
    expected value. If a mismatch occurs the download ISO is deleted.

base: core20
grade: stable
confinement: strict
adopt-info: ubuntu-iso-download
architectures:
  - build-on: amd64
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ubuntu-iso-download:
        command: bin/ubuntu-iso-download
        plugs:
            - network
            - network-bind
            - home

parts:
    ubuntu-iso-download:
        plugin: python
        source: https://github.com/powersj/ubuntu-iso-download
        source-type: git
        override-pull: |
            snapcraftctl pull
            DATE="$(date +%Y.%m.%d)"
            GIT="$(git rev-parse --short HEAD)"
            snapcraftctl set-version "${DATE}+git${GIT}"
    keyring:
        plugin: nil
        stage-packages:
            - ubuntu-keyring
        stage:
            - usr/share/keyrings/ubuntu-archive-keyring.gpg
    gpg:
        plugin: nil
        stage-packages:
            - gnupg
            - libassuan0
        stage:
            - usr/bin/gpg
            - usr/lib/x86_64-linux-gnu/libassuan.so.0
            - usr/lib/x86_64-linux-gnu/libassuan.so.0.8.3
